Scenario:
The data-set contains aggregate individual statistics for 67 NBA seasons. from basic box-score attributes such as points, assists, rebounds etc., to more advanced money-ball like features such as Value Over Replacement. 

Pre-Processing: 
In this task not all data will be used, only data in 2017. So it is necessary to do filtering at the beginning. Besides that there are some players who make team transfers in the NBA transfer market so that there is duplication of player data. Therefore you can use the df.drop_duplicates() syntax to solve this to produce the same output as the trainer. Delete columns that have as many missing values as the entire row of data. Then you can do additional preprocessing if needed or you can immediately process the data. 

Some goals of this project: 
1.	Who is the youngest and oldest player in the NBA in 2017 for each team (Tm) ?
2.	Which player has the most minutes played (MP) in each position (Pos)? 
3.	Which team has the highest average total rebound percentage (TRB%), assist percentage (AST%), steal percentage (STL%), and block percentage (BLK%)? 
4.	Who is the best player in your opinion based on his record stats? note: you can refer to variables point (PTS), assists, rebounds, or anything else. A combination of several variables would be nice. 
5.	Which team has the best average stat record of their players? Note: you can refer to points, assists, rebounds, or anything else. A combination of several variables would be nice

## Import Data and Load Library

In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler

data=pd.read_csv('Seasons_Stats.csv')
data.head(n=10)

,Unnamed: 0,Year,Player,Pos,Age,Tm,G,GS,MP,PER,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,0,1950.0,Curly Armstrong,G-F,31.0,FTW,63.0,NaN,NaN,NaN,...,0.705,NaN,NaN,NaN,176.0,NaN,NaN,NaN,217.0,458.0
1,1,1950.0,Cliff Barker,SG,29.0,INO,49.0,NaN,NaN,NaN,...,0.708,NaN,NaN,NaN,109.0,NaN,NaN,NaN,99.0,279.0
2,2,1950.0,Leo Barnhorst,SF,25.0,CHS,67.0,NaN,NaN,NaN,...,0.698,NaN,NaN,NaN,140.0,NaN,NaN,NaN,192.0,438.0
3,3,1950.0,Ed Bartels,F,24.0,TOT,15.0,NaN,NaN,NaN,...,0.559,NaN,NaN,NaN,20.0,NaN,NaN,NaN,29.0,63.0
4,4,1950.0,Ed Bartels,F,24.0,DNN,13.0,NaN,NaN,NaN,...,0.548,NaN,NaN,NaN,20.0,NaN,NaN,NaN,27.0,59.0
5,5,1950.0,Ed Bartels,F,24.0,NYK,2.0,NaN,NaN,NaN,...,0.667,NaN,NaN,NaN,0.0,NaN,NaN,NaN,2.0,4.0
6,6,1950.0,Ralph Beard,G,22.0,INO,60.0,NaN,NaN,NaN,...,0.762,NaN,NaN,NaN,233.0,NaN,NaN,NaN,132.0,895.0
7,7,1950.0,Gene Berce,G-F,23.0,TRI,3.0,NaN,NaN,NaN,...,0.000,NaN,NaN,NaN,2.0,NaN,NaN,NaN,6.0,10.0
8,8,1950.0,Charlie Black,F-C,28.0,TOT,65.0,NaN,NaN,NaN,...,0.651,NaN,NaN,NaN,163.0,NaN,NaN,NaN,273.0,661.0
9,9,1950.0,Charlie Black,F-C,28.0,FTW,36.0,NaN,NaN,NaN,...,0.632,NaN,NaN,NaN,75.0,NaN,NaN,NaN,140.0,382.0

##  Preprocessing Data

In [2]:
# Drop 1st Column
data=data.iloc[:,1:]
data.head(n=10)

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1950.0,Curly Armstrong,G-F,31.0,FTW,63.0,NaN,NaN,NaN,0.368,...,0.705,NaN,NaN,NaN,176.0,NaN,NaN,NaN,217.0,458.0
1,1950.0,Cliff Barker,SG,29.0,INO,49.0,NaN,NaN,NaN,0.435,...,0.708,NaN,NaN,NaN,109.0,NaN,NaN,NaN,99.0,279.0
2,1950.0,Leo Barnhorst,SF,25.0,CHS,67.0,NaN,NaN,NaN,0.394,...,0.698,NaN,NaN,NaN,140.0,NaN,NaN,NaN,192.0,438.0
3,1950.0,Ed Bartels,F,24.0,TOT,15.0,NaN,NaN,NaN,0.312,...,0.559,NaN,NaN,NaN,20.0,NaN,NaN,NaN,29.0,63.0
4,1950.0,Ed Bartels,F,24.0,DNN,13.0,NaN,NaN,NaN,0.308,...,0.548,NaN,NaN,NaN,20.0,NaN,NaN,NaN,27.0,59.0
5,1950.0,Ed Bartels,F,24.0,NYK,2.0,NaN,NaN,NaN,0.376,...,0.667,NaN,NaN,NaN,0.0,NaN,NaN,NaN,2.0,4.0
6,1950.0,Ralph Beard,G,22.0,INO,60.0,NaN,NaN,NaN,0.422,...,0.762,NaN,NaN,NaN,233.0,NaN,NaN,NaN,132.0,895.0
7,1950.0,Gene Berce,G-F,23.0,TRI,3.0,NaN,NaN,NaN,0.275,...,0.000,NaN,NaN,NaN,2.0,NaN,NaN,NaN,6.0,10.0
8,1950.0,Charlie Black,F-C,28.0,TOT,65.0,NaN,NaN,NaN,0.346,...,0.651,NaN,NaN,NaN,163.0,NaN,NaN,NaN,273.0,661.0
9,1950.0,Charlie Black,F-C,28.0,FTW,36.0,NaN,NaN,NaN,0.362,...,0.632,NaN,NaN,NaN,75.0,NaN,NaN,NaN,140.0,382.0

In [3]:
# Select Year=2017
data_2017=data[data['Year']==2017]
data_2017

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
24096,2017.0,Alex Abrines,SG,23.0,OKC,68.0,6.0,1055.0,10.1,0.560,...,0.898,18.0,68.0,86.0,40.0,37.0,8.0,33.0,114.0,406.0
24097,2017.0,Quincy Acy,PF,26.0,TOT,38.0,1.0,558.0,11.8,0.565,...,0.750,20.0,95.0,115.0,18.0,14.0,15.0,21.0,67.0,222.0
24098,2017.0,Quincy Acy,PF,26.0,DAL,6.0,0.0,48.0,-1.4,0.355,...,0.667,2.0,6.0,8.0,0.0,0.0,0.0,2.0,9.0,13.0
24099,2017.0,Quincy Acy,PF,26.0,BRK,32.0,1.0,510.0,13.1,0.587,...,0.754,18.0,89.0,107.0,18.0,14.0,15.0,19.0,58.0,209.0
24100,2017.0,Steven Adams,C,23.0,OKC,80.0,80.0,2389.0,16.5,0.589,...,0.611,282.0,333.0,615.0,86.0,88.0,78.0,146.0,195.0,905.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24686,2017.0,Cody Zeller,PF,24.0,CHO,62.0,58.0,1725.0,16.7,0.604,...,0.679,135.0,270.0,405.0,99.0,62.0,58.0,65.0,189.0,639.0
24687,2017.0,Tyler Zeller,C,27.0,BOS,51.0,5.0,525.0,13.0,0.508,...,0.564,43.0,81.0,124.0,42.0,7.0,21.0,20.0,61.0,178.0
24688,2017.0,Stephen Zimmerman,C,20.0,ORL,19.0,0.0,108.0,7.3,0.346,...,0.600,11.0,24.0,35.0,4.0,2.0,5.0,3.0,17.0,23.0
24689,2017.0,Paul Zipser,SF,22.0,CHI,44.0,18.0,843.0,6.9,0.503,...,0.775,15.0,110.0,125.0,36.0,15.0,16.0,40.0,78.0,240.0
24690,2017.0,Ivica Zubac,C,19.0,LAL,38.0,11.0,609.0,17.0,0.547,...,0.653,41.0,118.0,159.0,30.0,14.0,33.0,30.0,66.0,284.0

In [4]:
# Drop duplicates data
data_2017.drop_duplicates(subset='Player', inplace=True)
data_2017

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
24096,2017.0,Alex Abrines,SG,23.0,OKC,68.0,6.0,1055.0,10.1,0.560,...,0.898,18.0,68.0,86.0,40.0,37.0,8.0,33.0,114.0,406.0
24097,2017.0,Quincy Acy,PF,26.0,TOT,38.0,1.0,558.0,11.8,0.565,...,0.750,20.0,95.0,115.0,18.0,14.0,15.0,21.0,67.0,222.0
24100,2017.0,Steven Adams,C,23.0,OKC,80.0,80.0,2389.0,16.5,0.589,...,0.611,282.0,333.0,615.0,86.0,88.0,78.0,146.0,195.0,905.0
24101,2017.0,Arron Afflalo,SG,31.0,SAC,61.0,45.0,1580.0,9.0,0.559,...,0.892,9.0,116.0,125.0,78.0,21.0,7.0,42.0,104.0,515.0
24102,2017.0,Alexis Ajinca,C,28.0,NOP,39.0,15.0,584.0,12.9,0.529,...,0.725,46.0,131.0,177.0,12.0,20.0,22.0,31.0,77.0,207.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24686,2017.0,Cody Zeller,PF,24.0,CHO,62.0,58.0,1725.0,16.7,0.604,...,0.679,135.0,270.0,405.0,99.0,62.0,58.0,65.0,189.0,639.0
24687,2017.0,Tyler Zeller,C,27.0,BOS,51.0,5.0,525.0,13.0,0.508,...,0.564,43.0,81.0,124.0,42.0,7.0,21.0,20.0,61.0,178.0
24688,2017.0,Stephen Zimmerman,C,20.0,ORL,19.0,0.0,108.0,7.3,0.346,...,0.600,11.0,24.0,35.0,4.0,2.0,5.0,3.0,17.0,23.0
24689,2017.0,Paul Zipser,SF,22.0,CHI,44.0,18.0,843.0,6.9,0.503,...,0.775,15.0,110.0,125.0,36.0,15.0,16.0,40.0,78.0,240.0
24690,2017.0,Ivica Zubac,C,19.0,LAL,38.0,11.0,609.0,17.0,0.547,...,0.653,41.0,118.0,159.0,30.0,14.0,33.0,30.0,66.0,284.0

In [5]:
# Missing value check
data_2017.isnull().sum()

Year        0
Player      0
Pos         0
Age         0
Tm          0
G           0
GS          0
MP          0
PER         0
TS%         1
3PAr        1
FTr         1
ORB%        0
DRB%        0
TRB%        0
AST%        0
STL%        0
BLK%        0
TOV%        1
USG%        0
blanl     486
OWS         0
DWS         0
WS          0
WS/48       0
blank2    486
OBPM        0
DBPM        0
BPM         0
VORP        0
FG          0
FGA         0
FG%         1
3P          0
3PA         0
3P%        36
2P          0
2PA         0
2P%         2
eFG%        1
FT          0
FTA         0
FT%        15
ORB         0
DRB         0
TRB         0
AST         0
STL         0
BLK         0
TOV         0
PF          0
PTS         0
dtype: int64

In [6]:
# Check type data in each column
data_2017.dtypes

Year      float64
Player     object
Pos        object
Age       float64
Tm         object
G         float64
GS        float64
MP        float64
PER       float64
TS%       float64
3PAr      float64
FTr       float64
ORB%      float64
DRB%      float64
TRB%      float64
AST%      float64
STL%      float64
BLK%      float64
TOV%      float64
USG%      float64
blanl     float64
OWS       float64
DWS       float64
WS        float64
WS/48     float64
blank2    float64
OBPM      float64
DBPM      float64
BPM       float64
VORP      float64
FG        float64
FGA       float64
FG%       float64
3P        float64
3PA       float64
3P%       float64
2P        float64
2PA       float64
2P%       float64
eFG%      float64
FT        float64
FTA       float64
FT%       float64
ORB       float64
DRB       float64
TRB       float64
AST       float64
STL       float64
BLK       float64
TOV       float64
PF        float64
PTS       float64
dtype: object

In [7]:
# Drop column blan1 and blank1 that has 486 missing value 
data_2017 = data_2017.drop(['blanl', 'blank2'], axis = 1)
data_2017

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
24096,2017.0,Alex Abrines,SG,23.0,OKC,68.0,6.0,1055.0,10.1,0.560,...,0.898,18.0,68.0,86.0,40.0,37.0,8.0,33.0,114.0,406.0
24097,2017.0,Quincy Acy,PF,26.0,TOT,38.0,1.0,558.0,11.8,0.565,...,0.750,20.0,95.0,115.0,18.0,14.0,15.0,21.0,67.0,222.0
24100,2017.0,Steven Adams,C,23.0,OKC,80.0,80.0,2389.0,16.5,0.589,...,0.611,282.0,333.0,615.0,86.0,88.0,78.0,146.0,195.0,905.0
24101,2017.0,Arron Afflalo,SG,31.0,SAC,61.0,45.0,1580.0,9.0,0.559,...,0.892,9.0,116.0,125.0,78.0,21.0,7.0,42.0,104.0,515.0
24102,2017.0,Alexis Ajinca,C,28.0,NOP,39.0,15.0,584.0,12.9,0.529,...,0.725,46.0,131.0,177.0,12.0,20.0,22.0,31.0,77.0,207.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24686,2017.0,Cody Zeller,PF,24.0,CHO,62.0,58.0,1725.0,16.7,0.604,...,0.679,135.0,270.0,405.0,99.0,62.0,58.0,65.0,189.0,639.0
24687,2017.0,Tyler Zeller,C,27.0,BOS,51.0,5.0,525.0,13.0,0.508,...,0.564,43.0,81.0,124.0,42.0,7.0,21.0,20.0,61.0,178.0
24688,2017.0,Stephen Zimmerman,C,20.0,ORL,19.0,0.0,108.0,7.3,0.346,...,0.600,11.0,24.0,35.0,4.0,2.0,5.0,3.0,17.0,23.0
24689,2017.0,Paul Zipser,SF,22.0,CHI,44.0,18.0,843.0,6.9,0.503,...,0.775,15.0,110.0,125.0,36.0,15.0,16.0,40.0,78.0,240.0
24690,2017.0,Ivica Zubac,C,19.0,LAL,38.0,11.0,609.0,17.0,0.547,...,0.653,41.0,118.0,159.0,30.0,14.0,33.0,30.0,66.0,284.0

In [8]:
# Imputation missing value with 0 (assuming that missing doesn't have a score)
data_2017.fillna(0, inplace = True)
data_2017

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
24096,2017.0,Alex Abrines,SG,23.0,OKC,68.0,6.0,1055.0,10.1,0.560,...,0.898,18.0,68.0,86.0,40.0,37.0,8.0,33.0,114.0,406.0
24097,2017.0,Quincy Acy,PF,26.0,TOT,38.0,1.0,558.0,11.8,0.565,...,0.750,20.0,95.0,115.0,18.0,14.0,15.0,21.0,67.0,222.0
24100,2017.0,Steven Adams,C,23.0,OKC,80.0,80.0,2389.0,16.5,0.589,...,0.611,282.0,333.0,615.0,86.0,88.0,78.0,146.0,195.0,905.0
24101,2017.0,Arron Afflalo,SG,31.0,SAC,61.0,45.0,1580.0,9.0,0.559,...,0.892,9.0,116.0,125.0,78.0,21.0,7.0,42.0,104.0,515.0
24102,2017.0,Alexis Ajinca,C,28.0,NOP,39.0,15.0,584.0,12.9,0.529,...,0.725,46.0,131.0,177.0,12.0,20.0,22.0,31.0,77.0,207.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24686,2017.0,Cody Zeller,PF,24.0,CHO,62.0,58.0,1725.0,16.7,0.604,...,0.679,135.0,270.0,405.0,99.0,62.0,58.0,65.0,189.0,639.0
24687,2017.0,Tyler Zeller,C,27.0,BOS,51.0,5.0,525.0,13.0,0.508,...,0.564,43.0,81.0,124.0,42.0,7.0,21.0,20.0,61.0,178.0
24688,2017.0,Stephen Zimmerman,C,20.0,ORL,19.0,0.0,108.0,7.3,0.346,...,0.600,11.0,24.0,35.0,4.0,2.0,5.0,3.0,17.0,23.0
24689,2017.0,Paul Zipser,SF,22.0,CHI,44.0,18.0,843.0,6.9,0.503,...,0.775,15.0,110.0,125.0,36.0,15.0,16.0,40.0,78.0,240.0
24690,2017.0,Ivica Zubac,C,19.0,LAL,38.0,11.0,609.0,17.0,0.547,...,0.653,41.0,118.0,159.0,30.0,14.0,33.0,30.0,66.0,284.0

In [12]:
# Missing value check after imputation
data_2017.isnull().sum()

Year      0
Player    0
Pos       0
Age       0
Tm        0
G         0
GS        0
MP        0
PER       0
TS%       0
3PAr      0
FTr       0
ORB%      0
DRB%      0
TRB%      0
AST%      0
STL%      0
BLK%      0
TOV%      0
USG%      0
OWS       0
DWS       0
WS        0
WS/48     0
OBPM      0
DBPM      0
BPM       0
VORP      0
FG        0
FGA       0
FG%       0
3P        0
3PA       0
3P%       0
2P        0
2PA       0
2P%       0
eFG%      0
FT        0
FTA       0
FT%       0
ORB       0
DRB       0
TRB       0
AST       0
STL       0
BLK       0
TOV       0
PF        0
PTS       0
dtype: int64

In [9]:
# Reset index
data_2017=data_2017.reset_index(drop=True)
data_2017

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,2017.0,Alex Abrines,SG,23.0,OKC,68.0,6.0,1055.0,10.1,0.560,...,0.898,18.0,68.0,86.0,40.0,37.0,8.0,33.0,114.0,406.0
1,2017.0,Quincy Acy,PF,26.0,TOT,38.0,1.0,558.0,11.8,0.565,...,0.750,20.0,95.0,115.0,18.0,14.0,15.0,21.0,67.0,222.0
2,2017.0,Steven Adams,C,23.0,OKC,80.0,80.0,2389.0,16.5,0.589,...,0.611,282.0,333.0,615.0,86.0,88.0,78.0,146.0,195.0,905.0
3,2017.0,Arron Afflalo,SG,31.0,SAC,61.0,45.0,1580.0,9.0,0.559,...,0.892,9.0,116.0,125.0,78.0,21.0,7.0,42.0,104.0,515.0
4,2017.0,Alexis Ajinca,C,28.0,NOP,39.0,15.0,584.0,12.9,0.529,...,0.725,46.0,131.0,177.0,12.0,20.0,22.0,31.0,77.0,207.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,2017.0,Cody Zeller,PF,24.0,CHO,62.0,58.0,1725.0,16.7,0.604,...,0.679,135.0,270.0,405.0,99.0,62.0,58.0,65.0,189.0,639.0
482,2017.0,Tyler Zeller,C,27.0,BOS,51.0,5.0,525.0,13.0,0.508,...,0.564,43.0,81.0,124.0,42.0,7.0,21.0,20.0,61.0,178.0
483,2017.0,Stephen Zimmerman,C,20.0,ORL,19.0,0.0,108.0,7.3,0.346,...,0.600,11.0,24.0,35.0,4.0,2.0,5.0,3.0,17.0,23.0
484,2017.0,Paul Zipser,SF,22.0,CHI,44.0,18.0,843.0,6.9,0.503,...,0.775,15.0,110.0,125.0,36.0,15.0,16.0,40.0,78.0,240.0
485,2017.0,Ivica Zubac,C,19.0,LAL,38.0,11.0,609.0,17.0,0.547,...,0.653,41.0,118.0,159.0,30.0,14.0,33.0,30.0,66.0,284.0

##  Number 1

In [12]:
# Select data
data_2017_age=data_2017[['Player','Age','Tm']]
data_2017_age

                Player   Age   Tm
0         Alex Abrines  23.0  OKC
1           Quincy Acy  26.0  TOT
2         Steven Adams  23.0  OKC
3        Arron Afflalo  31.0  SAC
4        Alexis Ajinca  28.0  NOP
..                 ...   ...  ...
481        Cody Zeller  24.0  CHO
482       Tyler Zeller  27.0  BOS
483  Stephen Zimmerman  20.0  ORL
484        Paul Zipser  22.0  CHI
485        Ivica Zubac  19.0  LAL

[486 rows x 3 columns]

In [13]:
# Youngest player for each team
data_2017_age_youngest=data_2017_age.loc[data_2017_age.groupby('Tm')['Age'].idxmin()].reset_index(drop=True)
data_2017_age_youngest

                     Player   Age   Tm
0           DeAndre' Bembry  22.0  ATL
1              Jaylen Brown  20.0  BOS
2          Isaiah Whitehead  21.0  BRK
3              Bobby Portis  21.0  CHI
4            Christian Wood  21.0  CHO
5                Kay Felder  21.0  CLE
6                Ben Bentil  21.0  DAL
7              Jamal Murray  19.0  DEN
8            Henry Ellenson  20.0  DET
9              Kevon Looney  20.0  GSW
10           Chinanu Onuaku  20.0  HOU
11             Myles Turner  20.0  IND
12            Diamond Stone  19.0  LAC
13           Brandon Ingram  19.0  LAL
14             Wade Baldwin  20.0  MEM
15          Justise Winslow  20.0  MIA
16               Thon Maker  19.0  MIL
17               Tyus Jones  20.0  MIN
18            Cheick Diallo  20.0  NOP
19       Kristaps Porzingis  21.0  NYK
20         Domantas Sabonis  20.0  OKC
21        Stephen Zimmerman  20.0  ORL
22  Timothe Luwawu-Cabarrot  21.0  PHI
23            Dragan Bender  19.0  PHO
24              Noah Vonleh  21.0  POR
25     Georgios Papagiannis  19.0  SAC
26          Dejounte Murray  20.0  SAS
27            Bruno Caboclo  21.0  TOR
28         Chris McCullough  21.0  TOT
29               Dante Exum  21.0  UTA
30              Kelly Oubre  21.0  WAS

In [14]:
# Oldest player for each team
data_2017_age_oldest=data_2017_age.loc[data_2017_age.groupby('Tm')['Age'].idxmax()].reset_index(drop=True)
data_2017_age_oldest

             Player   Age   Tm
0         Gary Neal  32.0  ATL
1      Gerald Green  31.0  BOS
2        Luis Scola  36.0  BRK
3       Dwyane Wade  35.0  CHI
4     Brian Roberts  31.0  CHO
5    Chris Andersen  38.0  CLE
6     Dirk Nowitzki  38.0  DAL
7       Mike Miller  36.0  DEN
8        Beno Udrih  34.0  DET
9        David West  36.0  GSW
10     Nene Hilario  34.0  HOU
11     Aaron Brooks  32.0  IND
12      Paul Pierce  39.0  LAC
13      Metta World  37.0  LAL
14     Vince Carter  40.0  MEM
15    Udonis Haslem  36.0  MIA
16      Jason Terry  39.0  MIL
17       John Lucas  34.0  MIN
18     Jarrett Jack  33.0  NOP
19  Carmelo Anthony  32.0  NYK
20    Nick Collison  36.0  OKC
21      C.J. Watson  32.0  ORL
22   Tiago Splitter  32.0  PHI
23  Leandro Barbosa  34.0  PHO
24      Evan Turner  28.0  POR
25    Arron Afflalo  31.0  SAC
26    Manu Ginobili  39.0  SAS
27  DeMarre Carroll  30.0  TOR
28      Matt Barnes  36.0  TOT
29      Joe Johnson  35.0  UTA
30    Marcin Gortat  32.0  WAS

##  Number 2

In [15]:
# Select data
data_2017_minute=data_2017[['Player','Pos','Tm','MP']]
data_2017_minute

                Player Pos   Tm      MP
0         Alex Abrines  SG  OKC  1055.0
1           Quincy Acy  PF  TOT   558.0
2         Steven Adams   C  OKC  2389.0
3        Arron Afflalo  SG  SAC  1580.0
4        Alexis Ajinca   C  NOP   584.0
..                 ...  ..  ...     ...
481        Cody Zeller  PF  CHO  1725.0
482       Tyler Zeller   C  BOS   525.0
483  Stephen Zimmerman   C  ORL   108.0
484        Paul Zipser  SF  CHI   843.0
485        Ivica Zubac   C  LAL   609.0

[486 rows x 4 columns]

In [16]:
# Most minutes played in each position
data_2017_most_minute=data_2017_minute.loc[data_2017_minute.groupby('Pos')['MP'].idxmax()].reset_index(drop=True)
data_2017_most_minute

               Player   Pos   Tm      MP
0  Karl-Anthony Towns     C  MIN  3030.0
1     Harrison Barnes    PF  DAL  2803.0
2   Joffrey Lauvergne  PF-C  TOT   980.0
3        James Harden    PG  HOU  2947.0
4      Andrew Wiggins    SF  MIN  3048.0
5       C.J. McCollum    SG  POR  2796.0

##  Number 3

In [17]:
# Select data
data_2017_average=data_2017[['Tm','TRB%','AST%','STL%','BLK%']]
data_2017_average=data_2017_average.groupby('Tm').mean()
data_2017_average

          TRB%       AST%      STL%      BLK%
Tm
ATL   9.680000  14.120000  1.500000  1.693333
BOS  10.360000  14.573333  1.366667  1.493333
BRK   9.757143  15.000000  1.457143  1.400000
CHI   9.738462  13.061538  1.584615  1.315385
CHO   9.264286  14.042857  1.235714  1.371429
CLE  10.142857  11.978571  1.492857  1.885714
DAL  10.400000  14.162500  1.287500  1.643750
DEN  10.600000  15.860000  1.880000  0.953333
DET  10.326667  13.200000  1.260000  1.173333
GSW  11.426667  13.960000  1.733333  2.740000
HOU   9.761538  12.823077  1.646154  1.600000
IND  10.153333  12.446667  1.460000  1.540000
LAC  10.586667  12.033333  1.993333  2.053333
LAL  10.921429  11.942857  1.692857  1.585714
MEM  10.180000  13.293333  1.646667  1.920000
MIA  10.057143  12.728571  1.485714  1.600000
MIL   9.326667  13.146667  1.533333  1.986667
MIN   9.992857  12.664286  2.371429  1.585714
NOP   9.392308  13.415385  1.600000  1.607692
NYK  11.192857  11.921429  1.507143  1.964286
OKC  10.450000  13.891667  1.483333  1.800000
ORL   9.337500  12.225000  1.250000  1.243750
PHI  10.860000  15.040000  1.333333  1.786667
PHO   9.841176  11.029412  1.400000  1.458824
POR   9.638462  12.400000  1.430769  1.438462
SAC   9.123077  14.107692  1.584615  1.492308
SAS   9.687500  14.900000  1.512500  1.906250
TOR  10.671429  11.571429  1.928571  1.978571
TOT   9.490566  12.096226  1.469811  1.841509
UTA  10.386667  12.673333  1.540000  1.726667
WAS  13.450000  11.314286  1.535714  1.292857

In [18]:
# Team with highest TRB%
data_2017_average_trb=data_2017_average[data_2017_average['TRB%']==data_2017_average['TRB%'].max()]
data_2017_average_trb=data_2017_average_trb[['TRB%']]
data_2017_average_trb

      TRB%
Tm
WAS  13.45

In [19]:
# Team with highest AST%
data_2017_average_ast=data_2017_average[data_2017_average['AST%']==data_2017_average['AST%'].max()]
data_2017_average_ast=data_2017_average_ast[['AST%']]
data_2017_average_ast

      AST%
Tm
DEN  15.86

In [20]:
# Team with highest STL%
data_2017_average_stl=data_2017_average[data_2017_average['STL%']==data_2017_average['STL%'].max()]
data_2017_average_stl=data_2017_average_stl[['STL%']]
data_2017_average_stl

         STL%
Tm
MIN  2.371429

In [21]:
# Team with highest BLK%
data_2017_average_blk=data_2017_average[data_2017_average['BLK%']==data_2017_average['BLK%'].max()]
data_2017_average_blk=data_2017_average_blk[['BLK%']]
data_2017_average_blk

     BLK%
Tm
GSW  2.74

##  Number 4

In [22]:
# Scaliing G until PTS (0-1)
data_2017_best_player=data_2017
min_max_scaler = MinMaxScaler()
data_2017_best_player[list(data_2017)[5:]] = min_max_scaler.fit_transform(data_2017_best_player[list(data_2017)[5:]])
data_2017_best_player

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,2017.0,Alex Abrines,SG,23.0,OKC,0.827160,0.073171,0.345914,0.564155,0.700876,...,0.898,0.052174,0.083231,0.077061,0.044150,0.235669,0.037383,0.071121,0.410072,0.158718
1,2017.0,Quincy Acy,PF,26.0,TOT,0.456790,0.012195,0.182803,0.598778,0.707134,...,0.750,0.057971,0.116279,0.103047,0.019868,0.089172,0.070093,0.045259,0.241007,0.086787
2,2017.0,Steven Adams,C,23.0,OKC,0.975309,0.975610,0.783722,0.694501,0.737171,...,0.611,0.817391,0.407589,0.551075,0.094923,0.560510,0.364486,0.314655,0.701439,0.353792
3,2017.0,Arron Afflalo,SG,31.0,SAC,0.740741,0.548780,0.518215,0.541752,0.699625,...,0.892,0.026087,0.141983,0.112007,0.086093,0.133758,0.032710,0.090517,0.374101,0.201329
4,2017.0,Alexis Ajinca,C,28.0,NOP,0.469136,0.182927,0.191336,0.621181,0.662078,...,0.725,0.133333,0.160343,0.158602,0.013245,0.127389,0.102804,0.066810,0.276978,0.080923
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,2017.0,Cody Zeller,PF,24.0,CHO,0.753086,0.707317,0.565802,0.698574,0.755945,...,0.679,0.391304,0.330477,0.362903,0.109272,0.394904,0.271028,0.140086,0.679856,0.249805
482,2017.0,Tyler Zeller,C,27.0,BOS,0.617284,0.060976,0.171972,0.623218,0.635795,...,0.564,0.124638,0.099143,0.111111,0.046358,0.044586,0.098131,0.043103,0.219424,0.069586
483,2017.0,Stephen Zimmerman,C,20.0,ORL,0.222222,0.000000,0.035117,0.507128,0.433041,...,0.600,0.031884,0.029376,0.031362,0.004415,0.012739,0.023364,0.006466,0.061151,0.008991
484,2017.0,Paul Zipser,SF,22.0,CHI,0.530864,0.219512,0.276337,0.498982,0.629537,...,0.775,0.043478,0.134639,0.112007,0.039735,0.095541,0.074766,0.086207,0.280576,0.093823
485,2017.0,Ivica Zubac,C,19.0,LAL,0.456790,0.134146,0.199541,0.704684,0.684606,...,0.653,0.118841,0.144431,0.142473,0.033113,0.089172,0.154206,0.064655,0.237410,0.111024

In [23]:
# Calculate avg_rating based on avergae G until PTS
data_2017_best_player['Avg_Rating']=data_2017_best_player[list(data_2017)[5:]].mean(axis=1)
data_2017_best_player

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Avg_Rating
0,2017.0,Alex Abrines,SG,23.0,OKC,0.827160,0.073171,0.345914,0.564155,0.700876,...,0.052174,0.083231,0.077061,0.044150,0.235669,0.037383,0.071121,0.410072,0.158718,0.268483
1,2017.0,Quincy Acy,PF,26.0,TOT,0.456790,0.012195,0.182803,0.598778,0.707134,...,0.057971,0.116279,0.103047,0.019868,0.089172,0.070093,0.045259,0.241007,0.086787,0.235469
2,2017.0,Steven Adams,C,23.0,OKC,0.975309,0.975610,0.783722,0.694501,0.737171,...,0.817391,0.407589,0.551075,0.094923,0.560510,0.364486,0.314655,0.701439,0.353792,0.424301
3,2017.0,Arron Afflalo,SG,31.0,SAC,0.740741,0.548780,0.518215,0.541752,0.699625,...,0.026087,0.141983,0.112007,0.086093,0.133758,0.032710,0.090517,0.374101,0.201329,0.271095
4,2017.0,Alexis Ajinca,C,28.0,NOP,0.469136,0.182927,0.191336,0.621181,0.662078,...,0.133333,0.160343,0.158602,0.013245,0.127389,0.102804,0.066810,0.276978,0.080923,0.236012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,2017.0,Cody Zeller,PF,24.0,CHO,0.753086,0.707317,0.565802,0.698574,0.755945,...,0.391304,0.330477,0.362903,0.109272,0.394904,0.271028,0.140086,0.679856,0.249805,0.363128
482,2017.0,Tyler Zeller,C,27.0,BOS,0.617284,0.060976,0.171972,0.623218,0.635795,...,0.124638,0.099143,0.111111,0.046358,0.044586,0.098131,0.043103,0.219424,0.069586,0.224030
483,2017.0,Stephen Zimmerman,C,20.0,ORL,0.222222,0.000000,0.035117,0.507128,0.433041,...,0.031884,0.029376,0.031362,0.004415,0.012739,0.023364,0.006466,0.061151,0.008991,0.157535
484,2017.0,Paul Zipser,SF,22.0,CHI,0.530864,0.219512,0.276337,0.498982,0.629537,...,0.043478,0.134639,0.112007,0.039735,0.095541,0.074766,0.086207,0.280576,0.093823,0.232680
485,2017.0,Ivica Zubac,C,19.0,LAL,0.456790,0.134146,0.199541,0.704684,0.684606,...,0.118841,0.144431,0.142473,0.033113,0.089172,0.154206,0.064655,0.237410,0.111024,0.242505

In [24]:
# Sort the result
data_2017_best_player=data_2017_best_player.sort_values(['Avg_Rating'],ascending=[False])
data_2017_best_player

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Avg_Rating
457,2017.0,Russell Westbrook,PG,28.0,OKC,0.987654,0.987805,0.919265,0.981670,0.693367,...,0.397101,0.889841,0.774194,0.927152,0.847134,0.144860,0.943966,0.683453,1.000000,0.699472
171,2017.0,James Harden,PG,27.0,HOU,0.987654,0.987805,0.966853,0.914460,0.767209,...,0.275362,0.690330,0.590502,1.000000,0.764331,0.172897,1.000000,0.773381,0.921032,0.667842
432,2017.0,Karl-Anthony Towns,C,21.0,MIN,1.000000,1.000000,0.994093,0.887984,0.773467,...,0.857971,0.870257,0.902330,0.242826,0.363057,0.481308,0.456897,0.866906,0.805708,0.593027
15,2017.0,Giannis Antetokounmpo,SF,22.0,MIL,0.975309,0.975610,0.933377,0.890020,0.749687,...,0.411594,0.682987,0.627240,0.479029,0.834395,0.705607,0.504310,0.884892,0.716185,0.590386
219,2017.0,LeBron James,SF,32.0,CLE,0.901235,0.902439,0.916639,0.908350,0.774718,...,0.281159,0.664627,0.573477,0.713024,0.585987,0.205607,0.653017,0.482014,0.763878,0.576526
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,2017.0,Gary Neal,SG,32.0,ATL,0.012346,0.000000,0.005579,0.270876,0.285357,...,0.000000,0.001224,0.000896,0.001104,0.000000,0.000000,0.000000,0.003597,0.001564,0.092135
203,2017.0,Danuel House,SG,23.0,WAS,0.000000,0.000000,0.000000,0.606925,0.000000,...,0.000000,0.001224,0.000896,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.089280
143,2017.0,Patricio Garino,SG,23.0,ORL,0.049383,0.000000,0.013784,0.171079,0.000000,...,0.002899,0.007344,0.006272,0.000000,0.000000,0.000000,0.006466,0.014388,0.000000,0.077302
208,2017.0,R.J. Hunter,SG,23.0,CHI,0.024691,0.000000,0.002626,0.293279,0.000000,...,0.000000,0.001224,0.000896,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.074632
42,2017.0,Ben Bentil,PF,21.0,DAL,0.024691,0.000000,0.002954,0.000000,0.000000,...,0.000000,0.002448,0.001792,0.000000,0.000000,0.000000,0.002155,0.003597,0.000000,0.049934

In [25]:
# Top 5 player based on avg_rating
data_2017_best_player[['Player','Tm','Avg_Rating']].head(n=5).reset_index(drop=True)

                  Player   Tm  Avg_Rating
0      Russell Westbrook  OKC    0.699472
1           James Harden  HOU    0.667842
2     Karl-Anthony Towns  MIN    0.593027
3  Giannis Antetokounmpo  MIL    0.590386
4           LeBron James  CLE    0.576526

In [26]:
# Best player based on avg_rating
data_2017_best_player[['Player','Tm','Avg_Rating']].head(n=1).reset_index(drop=True)

              Player   Tm  Avg_Rating
0  Russell Westbrook  OKC    0.699472

##  Number 5

In [27]:
# Calculate average score for each team
data_2017_best_team=data_2017_best_player.groupby('Tm').mean()
data_2017_best_team

,Year,Age,G,GS,MP,PER,TS%,3PAr,FTr,ORB%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Avg_Rating
Tm,,,,,,,,,,,,,,,,,,,,,
ATL,2017.0,27.000000,0.623868,0.304878,0.385385,0.568771,0.594493,0.301867,0.146800,0.163498,...,0.150918,0.205141,0.196834,0.128992,0.260722,0.115576,0.164655,0.317026,0.199427,0.285542
BOS,2017.0,25.266667,0.721811,0.333333,0.431878,0.659470,0.701293,0.350733,0.165433,0.209632,...,0.143768,0.220155,0.205615,0.152244,0.261996,0.106231,0.148994,0.404317,0.230831,0.318226
BRK,2017.0,26.642857,0.663139,0.309233,0.397042,0.616090,0.666726,0.389071,0.147000,0.162955,...,0.133747,0.219706,0.202189,0.125670,0.242038,0.117156,0.175647,0.385663,0.204987,0.297190
CHI,2017.0,25.538462,0.687559,0.328330,0.421979,0.606455,0.599596,0.370462,0.106462,0.169640,...,0.187737,0.221542,0.220223,0.144846,0.290054,0.121855,0.153017,0.344494,0.215463,0.298833
CHO,2017.0,25.500000,0.626102,0.344948,0.425500,0.606634,0.622117,0.302643,0.161964,0.161597,...,0.126087,0.226875,0.205069,0.140807,0.242948,0.105474,0.125000,0.297790,0.224254,0.291366
CLE,2017.0,29.928571,0.604056,0.334495,0.397393,0.638202,0.674504,0.363143,0.161643,0.234927,...,0.151139,0.218745,0.206861,0.129927,0.212466,0.097130,0.144858,0.319116,0.225734,0.303591
DAL,2017.0,27.062500,0.546296,0.233232,0.320438,0.571665,0.594650,0.351125,0.119813,0.159458,...,0.085507,0.149633,0.135977,0.080229,0.192675,0.068341,0.087823,0.263264,0.157716,0.259152
DEN,2017.0,25.533333,0.610700,0.301626,0.399190,0.667210,0.709136,0.364733,0.193933,0.213688,...,0.158647,0.206854,0.200478,0.143046,0.222505,0.079751,0.151437,0.334532,0.222413,0.309250
DET,2017.0,25.466667,0.687243,0.333333,0.433016,0.624304,0.619358,0.284400,0.106467,0.196958,...,0.175459,0.231579,0.223775,0.127373,0.243737,0.096573,0.133908,0.351799,0.216549,0.297226
GSW,2017.0,27.600000,0.760494,0.329268,0.422470,0.672505,0.712307,0.216267,0.163333,0.265653,...,0.146087,0.227907,0.212007,0.179544,0.326964,0.169782,0.165948,0.367866,0.244384,0.334062
HOU,2017.0,26.230769,0.642925,0.374296,0.447022,0.643271,0.699047,0.407769,0.139500,0.206493,...,0.187291,0.239337,0.233113,0.162082,0.294953,0.115744,0.177885,0.396790,0.260931,0.326837
IND,2017.0,27.000000,0.725103,0.333333,0.431178,0.621589,0.649479,0.235733,0.126800,0.191381,...,0.143188,0.218605,0.204301,0.133848,0.282803,0.127414,0.154454,0.380096,0.223482,0.300567
LAC,2017.0,29.533333,0.698765,0.333333,0.431878,0.633401,0.662411,0.310400,0.136033,0.174905,...,0.142995,0.227662,0.210872,0.135982,0.260297,0.108723,0.147126,0.389928,0.232239,0.311530
LAL,2017.0,26.000000,0.650794,0.342334,0.404309,0.623509,0.651618,0.229429,0.131500,0.229223,...,0.185093,0.211750,0.212238,0.109902,0.254322,0.099800,0.155018,0.398510,0.198760,0.289024
MEM,2017.0,27.933333,0.676543,0.321138,0.421901,0.619823,0.650563,0.296533,0.145533,0.197465,...,0.169662,0.209874,0.206093,0.126049,0.265817,0.103738,0.141523,0.428297,0.209982,0.304485
MIA,2017.0,26.714286,0.665785,0.347561,0.454499,0.622491,0.655641,0.324857,0.122000,0.190114,...,0.177433,0.231596,0.224398,0.136235,0.262511,0.154873,0.156866,0.423176,0.232101,0.312928
MIL,2017.0,25.933333,0.680658,0.323577,0.421639,0.621589,0.666583,0.385333,0.106867,0.140177,...,0.134106,0.205386,0.191816,0.143267,0.276858,0.131464,0.153017,0.382494,0.217149,0.301528
MIN,2017.0,25.500000,0.682540,0.357143,0.457171,0.626418,0.635616,0.263500,0.117679,0.225964,...,0.192961,0.219969,0.220686,0.151687,0.291629,0.122830,0.167026,0.416238,0.239892,0.308293
NOP,2017.0,27.000000,0.532764,0.312383,0.367347,0.629485,0.689805,0.287308,0.151538,0.172858,...,0.121070,0.194897,0.180108,0.123281,0.231749,0.129403,0.125829,0.299668,0.184008,0.286325
NYK,2017.0,26.857143,0.711640,0.347561,0.426321,0.636020,0.650814,0.248143,0.129500,0.258012,...,0.197723,0.224690,0.225614,0.115973,0.236579,0.150200,0.147629,0.399794,0.222411,0.303919
OKC,2017.0,25.666667,0.665638,0.388211,0.427716,0.641718,0.657384,0.297500,0.119792,0.223384,...,0.206280,0.240616,0.239919,0.141464,0.289809,0.117991,0.190014,0.406175,0.238826,0.315058
ORL,2017.0,25.500000,0.604938,0.251524,0.355165,0.550916,0.583307,0.338125,0.143719,0.157319,...,0.126993,0.182298,0.172715,0.118308,0.203822,0.084988,0.128098,0.310701,0.174306,0.260587
PHI,2017.0,25.000000,0.558848,0.287805,0.363439,0.633265,0.668836,0.313800,0.130167,0.241065,...,0.124638,0.181069,0.171087,0.129213,0.248832,0.112773,0.166954,0.353237,0.180480,0.288063
PHO,2017.0,25.352941,0.575163,0.281923,0.351069,0.608123,0.637046,0.313176,0.150882,0.205100,...,0.150554,0.177335,0.176365,0.099403,0.220307,0.105827,0.148580,0.399281,0.193855,0.278314
POR,2017.0,24.384615,0.722697,0.316135,0.449825,0.614131,0.676615,0.366077,0.121192,0.173150,...,0.143813,0.216081,0.202647,0.123620,0.244488,0.110352,0.153515,0.418926,0.239069,0.307440
SAC,2017.0,26.384615,0.599240,0.294559,0.373533,0.630111,0.693367,0.298692,0.117000,0.165253,...,0.110368,0.162037,0.152743,0.110205,0.228809,0.081237,0.125497,0.340343,0.171558,0.277666
SAS,2017.0,28.750000,0.738426,0.312500,0.405912,0.643330,0.700954,0.306312,0.124719,0.164924,...,0.148913,0.212439,0.201557,0.134796,0.260350,0.141939,0.142376,0.336781,0.211029,0.315878
TOR,2017.0,24.571429,0.655203,0.333624,0.404121,0.652022,0.669408,0.268714,0.139786,0.248506,...,0.166667,0.202570,0.199821,0.112819,0.266606,0.114152,0.135930,0.384635,0.216045,0.308202
TOT,2017.0,26.377358,0.611693,0.200414,0.337474,0.612573,0.670579,0.336849,0.122726,0.172035,...,0.116653,0.176462,0.165247,0.093069,0.200937,0.098043,0.121869,0.321366,0.167532,0.275154
UTA,2017.0,26.200000,0.713580,0.333333,0.431922,0.653768,0.689111,0.304733,0.137000,0.186312,...,0.148986,0.226357,0.211768,0.121486,0.233546,0.127726,0.152443,0.370504,0.215220,0.314459
WAS,2017.0,25.714286,0.670194,0.355401,0.436706,0.627873,0.632487,0.230500,0.114643,0.175177,...,0.167495,0.222329,0.214542,0.143488,0.298453,0.110147,0.158559,0.418551,0.236541,0.303245

In [28]:
# Sort the data based on avg_rating
data_2017_best_team=data_2017_best_team.sort_values(['Avg_Rating'],ascending=[False])
data_2017_best_team

,Year,Age,G,GS,MP,PER,TS%,3PAr,FTr,ORB%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Avg_Rating
Tm,,,,,,,,,,,,,,,,,,,,,
GSW,2017.0,27.600000,0.760494,0.329268,0.422470,0.672505,0.712307,0.216267,0.163333,0.265653,...,0.146087,0.227907,0.212007,0.179544,0.326964,0.169782,0.165948,0.367866,0.244384,0.334062
HOU,2017.0,26.230769,0.642925,0.374296,0.447022,0.643271,0.699047,0.407769,0.139500,0.206493,...,0.187291,0.239337,0.233113,0.162082,0.294953,0.115744,0.177885,0.396790,0.260931,0.326837
BOS,2017.0,25.266667,0.721811,0.333333,0.431878,0.659470,0.701293,0.350733,0.165433,0.209632,...,0.143768,0.220155,0.205615,0.152244,0.261996,0.106231,0.148994,0.404317,0.230831,0.318226
SAS,2017.0,28.750000,0.738426,0.312500,0.405912,0.643330,0.700954,0.306312,0.124719,0.164924,...,0.148913,0.212439,0.201557,0.134796,0.260350,0.141939,0.142376,0.336781,0.211029,0.315878
OKC,2017.0,25.666667,0.665638,0.388211,0.427716,0.641718,0.657384,0.297500,0.119792,0.223384,...,0.206280,0.240616,0.239919,0.141464,0.289809,0.117991,0.190014,0.406175,0.238826,0.315058
UTA,2017.0,26.200000,0.713580,0.333333,0.431922,0.653768,0.689111,0.304733,0.137000,0.186312,...,0.148986,0.226357,0.211768,0.121486,0.233546,0.127726,0.152443,0.370504,0.215220,0.314459
MIA,2017.0,26.714286,0.665785,0.347561,0.454499,0.622491,0.655641,0.324857,0.122000,0.190114,...,0.177433,0.231596,0.224398,0.136235,0.262511,0.154873,0.156866,0.423176,0.232101,0.312928
LAC,2017.0,29.533333,0.698765,0.333333,0.431878,0.633401,0.662411,0.310400,0.136033,0.174905,...,0.142995,0.227662,0.210872,0.135982,0.260297,0.108723,0.147126,0.389928,0.232239,0.311530
DEN,2017.0,25.533333,0.610700,0.301626,0.399190,0.667210,0.709136,0.364733,0.193933,0.213688,...,0.158647,0.206854,0.200478,0.143046,0.222505,0.079751,0.151437,0.334532,0.222413,0.309250
MIN,2017.0,25.500000,0.682540,0.357143,0.457171,0.626418,0.635616,0.263500,0.117679,0.225964,...,0.192961,0.219969,0.220686,0.151687,0.291629,0.122830,0.167026,0.416238,0.239892,0.308293
TOR,2017.0,24.571429,0.655203,0.333624,0.404121,0.652022,0.669408,0.268714,0.139786,0.248506,...,0.166667,0.202570,0.199821,0.112819,0.266606,0.114152,0.135930,0.384635,0.216045,0.308202
POR,2017.0,24.384615,0.722697,0.316135,0.449825,0.614131,0.676615,0.366077,0.121192,0.173150,...,0.143813,0.216081,0.202647,0.123620,0.244488,0.110352,0.153515,0.418926,0.239069,0.307440
MEM,2017.0,27.933333,0.676543,0.321138,0.421901,0.619823,0.650563,0.296533,0.145533,0.197465,...,0.169662,0.209874,0.206093,0.126049,0.265817,0.103738,0.141523,0.428297,0.209982,0.304485
NYK,2017.0,26.857143,0.711640,0.347561,0.426321,0.636020,0.650814,0.248143,0.129500,0.258012,...,0.197723,0.224690,0.225614,0.115973,0.236579,0.150200,0.147629,0.399794,0.222411,0.303919
CLE,2017.0,29.928571,0.604056,0.334495,0.397393,0.638202,0.674504,0.363143,0.161643,0.234927,...,0.151139,0.218745,0.206861,0.129927,0.212466,0.097130,0.144858,0.319116,0.225734,0.303591
WAS,2017.0,25.714286,0.670194,0.355401,0.436706,0.627873,0.632487,0.230500,0.114643,0.175177,...,0.167495,0.222329,0.214542,0.143488,0.298453,0.110147,0.158559,0.418551,0.236541,0.303245
MIL,2017.0,25.933333,0.680658,0.323577,0.421639,0.621589,0.666583,0.385333,0.106867,0.140177,...,0.134106,0.205386,0.191816,0.143267,0.276858,0.131464,0.153017,0.382494,0.217149,0.301528
IND,2017.0,27.000000,0.725103,0.333333,0.431178,0.621589,0.649479,0.235733,0.126800,0.191381,...,0.143188,0.218605,0.204301,0.133848,0.282803,0.127414,0.154454,0.380096,0.223482,0.300567
CHI,2017.0,25.538462,0.687559,0.328330,0.421979,0.606455,0.599596,0.370462,0.106462,0.169640,...,0.187737,0.221542,0.220223,0.144846,0.290054,0.121855,0.153017,0.344494,0.215463,0.298833
DET,2017.0,25.466667,0.687243,0.333333,0.433016,0.624304,0.619358,0.284400,0.106467,0.196958,...,0.175459,0.231579,0.223775,0.127373,0.243737,0.096573,0.133908,0.351799,0.216549,0.297226
BRK,2017.0,26.642857,0.663139,0.309233,0.397042,0.616090,0.666726,0.389071,0.147000,0.162955,...,0.133747,0.219706,0.202189,0.125670,0.242038,0.117156,0.175647,0.385663,0.204987,0.297190
CHO,2017.0,25.500000,0.626102,0.344948,0.425500,0.606634,0.622117,0.302643,0.161964,0.161597,...,0.126087,0.226875,0.205069,0.140807,0.242948,0.105474,0.125000,0.297790,0.224254,0.291366
LAL,2017.0,26.000000,0.650794,0.342334,0.404309,0.623509,0.651618,0.229429,0.131500,0.229223,...,0.185093,0.211750,0.212238,0.109902,0.254322,0.099800,0.155018,0.398510,0.198760,0.289024
PHI,2017.0,25.000000,0.558848,0.287805,0.363439,0.633265,0.668836,0.313800,0.130167,0.241065,...,0.124638,0.181069,0.171087,0.129213,0.248832,0.112773,0.166954,0.353237,0.180480,0.288063
NOP,2017.0,27.000000,0.532764,0.312383,0.367347,0.629485,0.689805,0.287308,0.151538,0.172858,...,0.121070,0.194897,0.180108,0.123281,0.231749,0.129403,0.125829,0.299668,0.184008,0.286325
ATL,2017.0,27.000000,0.623868,0.304878,0.385385,0.568771,0.594493,0.301867,0.146800,0.163498,...,0.150918,0.205141,0.196834,0.128992,0.260722,0.115576,0.164655,0.317026,0.199427,0.285542
PHO,2017.0,25.352941,0.575163,0.281923,0.351069,0.608123,0.637046,0.313176,0.150882,0.205100,...,0.150554,0.177335,0.176365,0.099403,0.220307,0.105827,0.148580,0.399281,0.193855,0.278314
SAC,2017.0,26.384615,0.599240,0.294559,0.373533,0.630111,0.693367,0.298692,0.117000,0.165253,...,0.110368,0.162037,0.152743,0.110205,0.228809,0.081237,0.125497,0.340343,0.171558,0.277666
TOT,2017.0,26.377358,0.611693,0.200414,0.337474,0.612573,0.670579,0.336849,0.122726,0.172035,...,0.116653,0.176462,0.165247,0.093069,0.200937,0.098043,0.121869,0.321366,0.167532,0.275154
ORL,2017.0,25.500000,0.604938,0.251524,0.355165,0.550916,0.583307,0.338125,0.143719,0.157319,...,0.126993,0.182298,0.172715,0.118308,0.203822,0.084988,0.128098,0.310701,0.174306,0.260587
DAL,2017.0,27.062500,0.546296,0.233232,0.320438,0.571665,0.594650,0.351125,0.119813,0.159458,...,0.085507,0.149633,0.135977,0.080229,0.192675,0.068341,0.087823,0.263264,0.157716,0.259152

In [29]:
# Top 5 team based on avg_rating
data_2017_best_team[['Avg_Rating']].head(n=5)

     Avg_Rating
Tm
GSW    0.334062
HOU    0.326837
BOS    0.318226
SAS    0.315878
OKC    0.315058

In [30]:
# Best team based on avg_rating
data_2017_best_team[['Avg_Rating']].head(n=1)

     Avg_Rating
Tm
GSW    0.334062